# Generated by Django 2.2.14 on 2023-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20231202_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='link',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка'),
        ),
    ]
