# Generated by Django 2.2.14 on 2023-12-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_session_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cinema',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='cinemas', to='films.Cinema', verbose_name='Кинотеатр'),
        ),
    ]
