# Generated by Django 2.2.14 on 2023-12-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_session_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='map',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='Карта'),
        ),
    ]
