# Generated by Django 2.2.14 on 2023-12-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20231209_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='session',
        ),
    ]
