# Generated by Django 2.2.14 on 2023-12-09 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_cinema_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='cinemas', to='films.Session', verbose_name='Сессия'),
        ),
    ]
