# Generated by Django 2.2.14 on 2023-12-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_cinema_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='session',
        ),
    ]
