# Generated by Django 2.2.14 on 2023-12-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_cinema_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='cinema',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='films.Cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AlterField(
            model_name='session',
            name='film',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='films.Film', verbose_name='Фильм'),
        ),
    ]
