# Generated by Django 2.2.14 on 2023-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_auto_20231209_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.CharField(default='', max_length=40, verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=4, default=300, max_digits=19, verbose_name='Стоимость'),
        ),
    ]
