# Generated by Django 4.2 on 2023-12-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_auto_20231210_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, upload_to='cinema_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
