# Generated by Django 4.2 on 2023-12-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_cinema_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description',
            field=models.CharField(default='', max_length=1500, verbose_name='Описание'),
        ),
    ]
