# Generated by Django 4.2 on 2023-12-21 21:20

from django.db import migrations, models
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_remove_session_place_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='place_list',
            field=models.JSONField(default=films.models.small_hall, verbose_name='Места в зале'),
        ),
    ]
