# Generated by Django 4.2 on 2023-12-29 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_session_place_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('4D', '4D')], default='2D', max_length=2, verbose_name='Технология'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='films.session', verbose_name='Киносеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
