# Generated by Django 4.2 on 2023-12-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0027_ticket_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Стоимость'),
        ),
    ]
